services:
  - type: web
    name: certificatesite
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn flask_app:app"
    autoDeploy: false